---
title: "JSC370 HW5 - Interactive Visualization"
author: "Chloe Nguyen"
output: html_document
---

This website was created for JSC370 HW5.

Please refer to the 'Visualizations' tab for HW5 visualizations.

## About {.tabset}

### The Data

There are many ways to score in American football. A relatively reliable method to do so is by kicking a field goal. In this project, we'll visualize field goal kicks from the NFL 2018-2020 seasons through intactive plots.

This project works with data provided by the NFL's 2022 Big Data Bowl: https://www.kaggle.com/c/nfl-big-data-bowl-2022/overview

Team locations and names were retrieved from:

- https://github.com/Sinbad311/CloudProject/blob/master/NFL%20Stadium%20Latitude%20and%20Longtitude.csv

- https://gist.github.com/cnizzardini/13d0a072adb35a0d5817


### Why Football Field Goals?

The creator of this project, Chloe Nguyen, is particularly interested in the kicker position (and hence is interested in investigating more on football field goals for JSC370 projects) because it is the only reasonable football position she can potentially play- as a relatively small person who cannot throw or catch a football. Chloe is a (bandwaggon) Bengals fan and is still devasted over their lost at the last Super Bowl. She is very excited that JSC370 has allowed her the opporunity to unite her interests of football and data science.


### The Assignment

The aim of this project is to better learn and explore interactive visualizations- building off of the JSC370 midterm.




